# Config file for automatic testing at travis-ci.org

language: python
dist: focal
python:
  - "3.11"
  - "3.10"
  - "3.9"
  - "3.8"
#  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install pytest
    - pip install pytest-cov

# Command to run tests, e.g. python setup.py test
script:
    - pytest --cov=cellmaps_utils tests/

after_success:
    - coveralls


